'use client';
import { useEffect, useState, type FormEvent } from 'react';
import { Search, Plus, Compass, Clapperboard, Gamepad2, Radio, Music2, Hexagon, Store, SlidersHorizontal, Bookmark, Heart, MessageCircle, ArrowUpRight, ArrowLeft, ChevronRight, ChevronLeft, Sparkles, Layers3, ShieldCheck, Wallet, Bell, LogOut, UserRound, UploadCloud, Scissors, Globe2, Check, Settings2, Play, LockKeyhole, Link2, Menu } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { NativeSelect } from '@/components/ui/native-select';
import { Checkbox } from '@/components/ui/checkbox';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { BrandLogo } from '@/components/brand-logo';
import { api } from '@/lib/api';
import { Composer } from './composer';
import { MediaPlayer } from './media-player';
import { matchesFeed, type Bootstrap, type Item, type Member, type Preferences, type Feed } from './types';
import './workspace.css';

const categories=[{id:'all',name:'For you',icon:Compass},{id:'video',name:'Videos',icon:Clapperboard},{id:'games',name:'Games',icon:Gamepad2},{id:'live',name:'Live feeds',icon:Radio},{id:'music',name:'Music & film',icon:Music2},{id:'nft',name:'NFTs',icon:Hexagon},{id:'store',name:'Store',icon:Store}];
const views=[{name:'Discover',icon:Compass},{name:'My studio',icon:Clapperboard},{name:'Feed builder',icon:SlidersHorizontal},{name:'Safety & filters',icon:ShieldCheck},{name:'Earnings',icon:Wallet}];
const integrations=[
 {title:'Portable identity',service:'AT Protocol OAuth',text:'Connect Bluesky identity, social graph, and cross-app publishing. Needs a verified OAuth client, secure token storage, and lexicon mapping.'},
 {title:'Live broadcast',service:'Streamplace',text:'Add signed live video and stream discovery. Needs a station endpoint, stream authorization, ingest, moderation, and playback integration.'},
 {title:'Creator payouts',service:'Payments & wallets',text:'Tips, subscriptions, seller payouts, and curator splits. Needs provider accounts, onboarding, verified webhooks, and a reviewed money flow.'},
 {title:'Media delivery',service:'Transcoding & CDN',text:'Add adaptive HLS/DASH renditions and delivery monitoring. Decentralized storage alone does not guarantee fast video playback.'},
 {title:'Creative AI',service:'On-device models',text:'Automatic captions, background removal, noise reduction, and beat sync require licensed models, browser capability checks, and performance testing.'},
 {title:'Community safety',service:'AT Protocol labelers',text:'Subscribe to community moderation services. Needs labeler identity verification, label ingestion, appeals, and enforcement policies.'},
];
const empty:Bootstrap={items:[],drafts:[],feeds:[],community_feeds:[],preferences:{liked:[],saved:[],muted_words:[],blocked_creators:[],show_demos:true}};

export function CreatorWorkspace({member,onLogout,logoutBusy}:{member:Member;onLogout:()=>void;logoutBusy:boolean}) {
 const [data,setData]=useState<Bootstrap>(empty);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [notice,setNotice]=useState('');
 const [view,setView]=useState('Discover');const [category,setCategory]=useState('all');const [query,setQuery]=useState('');const [feedId,setFeedId]=useState('all');const [slide,setSlide]=useState(0);const [navOpen,setNavOpen]=useState(false);const [saving,setSaving]=useState(false);
 const [dialog,setDialog]=useState<'create'|'view'|'updates'|null>(null);const [selected,setSelected]=useState<Item>();const [editing,setEditing]=useState<Item>();const [remix,setRemix]=useState<Item>();
 async function refresh(){setError('');try{setData(await api<Bootstrap>('/creator/bootstrap'));}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void refresh();},[]);
 function navigate(next:string){setView(next);setNavOpen(false);setNotice('');}
 function create(item?:Item,remixItem?:Item){setEditing(item);setRemix(remixItem);setDialog('create');}
 async function updatePrefs(next:Preferences){setSaving(true);setError('');try{await api('/creator/preferences',next);await refresh();return true;}catch(e){setError((e as Error).message);return false;}finally{setSaving(false);}}
 async function toggle(kind:'liked'|'saved',id:string){const current=data.preferences[kind];await updatePrefs({...data.preferences,[kind]:current.includes(id)?current.filter(i=>i!==id):[...current,id]});}
 const allFeeds=[...data.feeds,...data.community_feeds.filter(f=>!data.feeds.some(m=>m.id===f.id))];
 const activeFeed=allFeeds.find(f=>f.id===feedId);
 const filtered=data.items.filter(i=>(category==='all'||i.category===category)&&(feedId!=='saved'||data.preferences.saved.includes(i.id))&&(!activeFeed||matchesFeed(i,activeFeed))&&(!query||`${i.title} ${i.description} ${i.creator} ${i.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase())));
 const featured=filtered[slide%Math.max(filtered.length,1)];
 function openItem(item:Item){setSelected(item);setDialog('view');}
 const heading=view==='Discover'?'A world of possibilities.':view==='My studio'?'Your ideas live here.':view==='Feed builder'?'Your feed. Your rules.':view==='Safety & filters'?'Make this space yours.':view==='Earnings'?'Create on your terms.':'Your creator profile.';
 return <main className="creator-app"><aside className={`cw-sidebar ${navOpen?'is-open':''}`}><BrandLogo/><span className="cw-sidebar-caption">CREATOR PORTAL</span><nav aria-label="Creator workspace">{views.map(({name,icon:Icon})=><Button variant="ghost" key={name} className={view===name?'is-active':''} onClick={()=>navigate(name)}><Icon size={19}/>{name}{name==='My studio'&&data.drafts.length>0&&<span className="cw-counter">{data.drafts.length}</span>}</Button>)}</nav><div className="cw-sidebar-divider"/><span className="cw-sidebar-caption">YOUR FEEDS</span><div className="cw-saved-feeds">{data.feeds.slice(0,4).map(feed=><Button variant="ghost" key={feed.id} onClick={()=>{setFeedId(feed.id);setCategory('all');navigate('Discover');}}><span className="cw-feed-dot"/>{feed.name}</Button>)}<Button variant="ghost" onClick={()=>navigate('Feed builder')}><Plus size={17}/> Build a feed</Button></div><div className="cw-local-card"><Globe2 size={20}/><strong>An open world starts here.</strong><p>Local workspace. Network integrations are not connected.</p><button onClick={()=>navigate('Earnings')}>See what's next <ArrowUpRight size={13}/></button></div><div className="cw-sidebar-bottom"><a href="/"><ArrowLeft size={15}/> Back to Ziipa.com</a><Button variant="ghost" onClick={onLogout} disabled={logoutBusy}><LogOut size={15}/> Sign out</Button></div></aside>
 <div className="cw-body"><header className="cw-topbar"><Button variant="ghost" className="cw-menu" aria-label="Toggle navigation" aria-expanded={navOpen} onClick={()=>setNavOpen(!navOpen)}><Menu size={21}/></Button><div className="cw-breadcrumb">Your space <ChevronRight size={12}/><strong>{view}</strong></div><label className="cw-search"><Search size={18}/><Input value={query} onChange={e=>{setQuery(e.target.value);setView('Discover');}} aria-label="Search creations, creators and tags" placeholder="Search creations, creators, inspiration…"/></label><span className="cw-local-badge"><i/> LOCAL PREVIEW</span><Button variant="ghost" size="icon" aria-label="Workspace updates" onClick={()=>setDialog('updates')}><Bell size={19}/></Button><Button className="cw-avatar" onClick={()=>navigate('Account')} aria-label="Open your profile">{member.name.charAt(0).toUpperCase()}</Button></header>
 <div className="cw-content"><div className="cw-heading"><div><span className="cw-overline">{view==='Discover'?'DISCOVER SOMETHING YOU LOVE':'ZIIPA CREATOR WORKSPACE'}</span><h1>{heading}</h1><p>{view==='Discover'?'Watch. Play. Connect. Create. All in your world.':view==='My studio'?'From your first draft to your next local release.':view==='Feed builder'?'Curate what you see, and share the recipe with your community.':view==='Safety & filters'?'Choose the content and creators you want in your feed.':view==='Earnings'?'The foundation for your creator business.':'One space for your identity and creations.'}</p></div><Button className="cw-primary" onClick={()=>create()}><Plus size={18}/> Create</Button></div>
 {error&&<div className="cw-error" role="alert">{error} <Button variant="link" onClick={()=>void refresh()}>Retry</Button></div>}{notice&&<p className="cw-info" role="status">{notice}</p>}
 {loading?<div className="cw-empty" role="status"><Sparkles size={30}/><h2>Opening your creative world…</h2></div>:view==='Discover'?<>
 <nav className="cw-categories" aria-label="Content categories">{categories.map(({id,name,icon:Icon})=><Button variant="ghost" key={id} className={category===id?'selected':''} aria-pressed={category===id} onClick={()=>{setCategory(id);setSlide(0);}}><span><Icon size={22}/></span>{name}</Button>)}</nav>
 <div className="cw-discover-layout"><section className="cw-feed-column"><div className="cw-feed-toolbar"><div><Button variant="ghost" className={feedId==='all'?'active':''} onClick={()=>setFeedId('all')}>For you</Button><Button variant="ghost" className={feedId==='saved'?'active':''} onClick={()=>setFeedId('saved')}>Saved</Button></div><NativeSelect value={activeFeed?feedId:''} aria-label="Choose a custom feed" onChange={e=>setFeedId(e.target.value||'all')}><option value="">Custom feeds</option>{allFeeds.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</NativeSelect><Button variant="ghost" size="icon" aria-label="Edit feed filters" onClick={()=>navigate('Feed builder')}><SlidersHorizontal size={17}/></Button></div>
 {featured?<><article className={`cw-spotlight cw-spotlight-${featured.category}`}><img src={featured.cover} alt=""/><div className="cw-spotlight-shade"/><div className="cw-spotlight-top"><span><Music2 size={13}/> {categories.find(c=>c.id===featured.category)?.name}</span><span>{featured.demo?'DEMO COLLECTION':'LOCAL CREATION'}</span></div><div className="cw-spotlight-copy"><span>{featured.creator}</span><h2>{featured.title}</h2><p>{featured.tags.map(t=>`#${t}`).join('  ')}</p><Button onClick={()=>openItem(featured)}><Play size={16} fill="currentColor"/>{featured.media_url?'Watch now':'Explore collection'}</Button></div><div className="cw-carousel-controls"><Button size="icon" variant="ghost" aria-label="Previous featured creation" onClick={()=>setSlide(s=>(s+filtered.length-1)%filtered.length)}><ChevronLeft size={19}/></Button><span>{slide%filtered.length+1} / {filtered.length}</span><Button size="icon" variant="ghost" aria-label="Next featured creation" onClick={()=>setSlide(s=>s+1)}><ChevronRight size={19}/></Button></div></article><div className="cw-section-label"><h2>{query?'Search results':activeFeed?activeFeed.name:feedId==='saved'?'Your saved finds':'Made for your curiosity'}</h2><span>{filtered.length} creations</span></div><div className="cw-media-grid">{filtered.map(item=><article className="cw-media-card" key={item.id}><button className="cw-media-cover" onClick={()=>openItem(item)}><img src={item.cover} alt={item.title} loading="lazy"/><span className="cw-media-label">{item.label}</span><span className="cw-card-play">{item.media_url?<Play size={18}/>:<ArrowUpRight size={18}/>}</span></button><div className="cw-card-title"><button onClick={()=>openItem(item)}>{item.title}</button><Button variant="ghost" size="icon-sm" aria-label={`${data.preferences.saved.includes(item.id)?'Unsave':'Save'} ${item.title}`} disabled={saving} onClick={()=>void toggle('saved',item.id)}><Bookmark size={16} fill={data.preferences.saved.includes(item.id)?'currentColor':'none'}/></Button></div><p><span className="cw-mini-avatar">{item.creator[0]}</span>{item.creator}{item.demo&&<small>DEMO</small>}</p></article>)}</div></>:<div className="cw-empty"><Compass size={32}/><h2>No creations here yet.</h2><p>Try a different category, clear your search, or adjust your filters.</p><Button variant="outline" onClick={()=>{setQuery('');setCategory('all');setFeedId('all');}}>Reset discovery filters</Button></div>}
 <p className="cw-footnote">Demo collections are illustrative. Only the sample film and uploaded media are playable. No active broadcasts or marketplace transactions.</p></section>
 <aside className="cw-right-rail"><article className="cw-creator-card"><div className="cw-creator-card-top"><span className="cw-avatar">{member.name[0].toUpperCase()}</span><span><strong>{member.name}</strong><small>YOUR CREATOR SPACE</small></span><Sparkles size={19}/></div><h3>What will you<br/>create today?</h3><p>Your ideas, your audience.<br/>Make something that feels like you.</p><Button className="cw-primary" onClick={()=>create()}><Plus size={16}/> Create a post</Button><div className="cw-studio-counts"><div><strong>{data.drafts.filter(d=>d.visibility==='published').length}</strong><span>Local posts</span></div><div><strong>{data.drafts.filter(d=>d.visibility==='draft').length}</strong><span>Drafts</span></div><div><strong>{data.feeds.length}</strong><span>Feeds</span></div></div></article><article className="cw-rail-section"><div><h3>A feed that feels like you</h3><SlidersHorizontal size={18}/></div><p>Less scrolling past. More finding your thing.</p><Button variant="outline" onClick={()=>navigate('Feed builder')}>Build your own feed <ArrowUpRight size={15}/></Button>{data.community_feeds.slice(0,2).map(f=><button className="cw-rail-feed" key={f.id} onClick={()=>{setFeedId(f.id);setCategory('all');}}><span className="cw-feed-dot"/><span>{f.name}<small>by {f.owner_name}</small></span><ChevronRight size={16}/></button>)}</article><article className="cw-rail-section cw-safety-card"><ShieldCheck size={23}/><h3>Your space, your boundaries.</h3><p>Fine-tune your feed with word filters and creator blocks.</p><button onClick={()=>navigate('Safety & filters')}>Manage your preferences <ArrowUpRight size={14}/></button></article><div className="cw-rail-footer"><a href="/">About Ziipa</a><button onClick={()=>navigate('Safety & filters')}>Safety</button><button onClick={()=>setDialog('updates')}>What's new</button><span>© 2026 Ziipa Inc.</span></div></aside></div></>
 :view==='My studio'?<><div className="cw-studio-summary"><div><Clapperboard/><strong>{data.drafts.length}</strong><span>Total creations</span></div><div><Scissors/><strong>{data.drafts.filter(d=>d.visibility==='draft').length}</strong><span>Work in progress</span></div><div><Layers3/><strong>{data.feeds.length}</strong><span>Curated feeds</span></div></div>{data.drafts.length?<div className="cw-media-grid cw-studio-grid">{data.drafts.map(item=><article className="cw-media-card" key={item.id}><button className="cw-media-cover" onClick={()=>create(item)}><img src={item.cover} alt=""/><span className="cw-media-label">{item.visibility==='published'?'Published locally':'Draft'}</span><span className="cw-card-play"><Scissors size={18}/></span></button><div className="cw-card-title"><button onClick={()=>create(item)}>{item.title}</button><ArrowUpRight size={16}/></div><p>{categories.find(c=>c.id===item.category)?.name} · {item.tags.join(', ')||'No tags yet'}</p></article>)}</div>:<div className="cw-empty"><UploadCloud size={38}/><h2>Big ideas start somewhere.</h2><p>Upload your first clip, create a collection draft, or plan your next live session.</p><Button className="cw-primary" onClick={()=>create()}>Create your first post <Plus size={16}/></Button></div>}</>
 :view==='Feed builder'?<FeedBuilder items={data.items} feeds={allFeeds} onSave={async input=>{await api('/creator/feeds',input);await refresh();setNotice('Feed saved. Select it in Discover or use it below.');}} onUse={feed=>{setFeedId(feed.id);setCategory('all');setQuery('');navigate('Discover');}}/>
 :view==='Safety & filters'?<Safety preferences={data.preferences} saving={saving} onSave={async prefs=>{if(await updatePrefs(prefs))setNotice('Your local feed preferences have been saved.');}}/>
 :view==='Earnings'?<><div className="cw-earnings-banner"><Wallet size={35}/><div><h2>Your creator economy starts with trust.</h2><p>Tips, memberships, seller payouts, and curator revenue sharing are planned. No wallet is connected and no funds can move in this local build.</p></div><span className="cw-status">NOT CONNECTED</span></div><div className="cw-integrations">{integrations.map(({title,service,text})=><article key={title}><span className="cw-status">PRODUCTION INTEGRATION</span><h3>{title}</h3><strong>{service}</strong><p>{text}</p></article>)}</div></>
 :<section className="cw-account"><span className="cw-avatar">{member.name[0].toUpperCase()}</span><h2>{member.name}</h2><span className="cw-status">{member.membership}</span><dl><dt>Email</dt><dd>{member.email}</dd><dt>Joined</dt><dd>{new Date(member.joined).toLocaleDateString()}</dd><dt>Identity</dt><dd>Local Ziipa account</dd><dt>AT Protocol</dt><dd>Not connected</dd></dl><p>Your profile is currently read-only. Email verification and password recovery are not enabled.</p><Button variant="outline" onClick={onLogout} disabled={logoutBusy}><LogOut size={16}/> Sign out</Button></section>}
 </div></div>
 <nav className="cw-mobile-dock" aria-label="Mobile creator navigation"><Button variant="ghost" className={view==='Discover'?'active':''} onClick={()=>navigate('Discover')}><Compass size={21}/><span>Discover</span></Button><Button variant="ghost" className={view==='My studio'?'active':''} onClick={()=>navigate('My studio')}><Clapperboard size={21}/><span>Studio</span></Button><Button className="cw-dock-add" aria-label="Create a post" onClick={()=>create()}><Plus size={25}/></Button><Button variant="ghost" className={view==='Feed builder'?'active':''} onClick={()=>navigate('Feed builder')}><SlidersHorizontal size={21}/><span>Feeds</span></Button><Button variant="ghost" onClick={()=>navigate('Account')}><UserRound size={21}/><span>Profile</span></Button></nav>
 <Dialog open={dialog!==null} onOpenChange={open=>{if(!open)setDialog(null);}}><DialogContent className={`cw-dialog ${dialog==='create'?'cw-dialog-wide':''}`}><DialogTitle>{dialog==='create'?(editing?'Edit your creation':remix?'Create a remix':'Create something yours'):dialog==='view'?selected?.title:'Your Ziipa workspace'}</DialogTitle><DialogDescription>{dialog==='create'?'Create, preview, and save in your local workspace.':dialog==='view'?(selected?.demo?'Demonstration content · local interactions only':`By ${selected?.creator} · local Ziipa post`):'What works now, and what comes next.'}</DialogDescription>{dialog==='create'&&<Composer key={editing?.id||remix?.id||'new'} item={editing} remix={remix} onSaved={async()=>{await refresh();setDialog(null);navigate('My studio');setNotice('Your creation has been saved.');}}/>}{dialog==='view'&&selected&&<Viewer item={selected} preferences={data.preferences} saving={saving} onToggle={toggle} onRemix={()=>create(undefined,selected)} onIntegration={()=>{setDialog(null);navigate('Earnings');}} onBlock={async()=>{await updatePrefs({...data.preferences,blocked_creators:[...new Set([...data.preferences.blocked_creators,selected.creator])]});setDialog(null);}}/>}{dialog==='updates'&&<div className="cw-updates"><p><Check size={18}/> Upload and play local media; save drafts and publish locally.</p><p><Check size={18}/> Save feeds, captions, bookmarks, comments, and safety preferences.</p><p><LockKeyhole size={18}/> AT Protocol, broadcasting, payouts, minting, and AI processing are not connected.</p><Button className="cw-primary" onClick={()=>{setDialog(null);navigate('Earnings');}}>View production integrations <ArrowUpRight size={16}/></Button></div>}</DialogContent></Dialog>
 </main>;
}

function FeedBuilder({items,feeds,onSave,onUse}:{items:Item[];feeds:Feed[];onSave:(f:Omit<Feed,'id'>)=>Promise<void>;onUse:(f:Feed)=>void}) {
 const [form,setForm]=useState({name:'',category:'all',tag:'',city:'',creator:'',shared:false});const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const matching=items.filter(i=>matchesFeed(i,form));
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await onSave(form);setForm({...form,name:''});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><div className="cw-tool-grid"><form className="cw-panel cw-fields" onSubmit={submit}><span className="cw-overline">BUILD A CUSTOM FEED</span><h2>Curated by you.</h2><label>Feed name<Input required maxLength={80} placeholder="My after-hours inspiration" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Content category<NativeSelect value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(c=><option key={c.id} value={c.id}>{c.id==='all'?'All categories':c.name}</option>)}</NativeSelect></label><label>Contains tag<Input maxLength={40} placeholder="music" value={form.tag} onChange={e=>setForm({...form,tag:e.target.value})}/></label><label>Creator name contains<Input maxLength={100} placeholder="Any creator" value={form.creator} onChange={e=>setForm({...form,creator:e.target.value})}/></label><label>City contains<Input maxLength={80} placeholder="Any city" value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/><small>Matches declared city text; no GPS or geographic radius is used.</small></label><label className="cw-checkbox-label"><Checkbox checked={form.shared} onCheckedChange={checked=>setForm({...form,shared:checked===true})}/> Share these rules with local members</label>{error&&<p className="cw-error" role="alert">{error}</p>}<Button className="cw-primary" type="submit" disabled={busy}><Plus size={17}/>{busy?'Saving…':'Save custom feed'}</Button><small>Rules combine with AND. Your personal safety filters still apply. No external algorithm or ranking service is used.</small></form><section className="cw-panel"><span className="cw-overline">LIVE PREVIEW</span><h2>{matching.length} matching creations</h2><p className="cw-muted">See exactly what your rules bring into the feed.</p>{matching.length?matching.slice(0,6).map(i=><div className="cw-preview-row" key={i.id}><img src={i.cover} alt=""/><div><strong>{i.title}</strong><p>{i.creator} · {i.tags.join(', ')}</p></div></div>):<div className="cw-empty"><Search size={28}/><p>No matches. Try fewer filters.</p></div>}</section></div><div className="cw-section-label"><h2>Feeds to make your own</h2><span>Local community</span></div><div className="cw-feed-cards">{feeds.map(f=><article className="cw-panel" key={f.id}><SlidersHorizontal size={24}/><h3>{f.name}</h3><p>{[f.category!=='all'&&f.category,f.tag&&`#${f.tag}`,f.city,f.creator].filter(Boolean).join(' · ')||'All creations'}</p><small>{f.shared?'Shared with local members':'Private feed'}</small><Button variant="outline" onClick={()=>onUse(f)}>Use feed <ArrowUpRight size={15}/></Button></article>)}</div></>;
}

function Safety({preferences,saving,onSave}:{preferences:Preferences;saving:boolean;onSave:(p:Preferences)=>Promise<void>}) {
 const [words,setWords]=useState(preferences.muted_words.join(', '));const [creators,setCreators]=useState(preferences.blocked_creators.join(', '));const [demos,setDemos]=useState(preferences.show_demos);
 return <div className="cw-tool-grid"><form className="cw-panel cw-fields" onSubmit={e=>{e.preventDefault();void onSave({...preferences,muted_words:words.split(',').map(t=>t.trim()).filter(Boolean),blocked_creators:creators.split(',').map(t=>t.trim()).filter(Boolean),show_demos:demos});}}><ShieldCheck size={30}/><h2>Your personal filters</h2><label>Muted words<Textarea value={words} onChange={e=>setWords(e.target.value)} placeholder="Words or phrases, separated by commas"/><small>Hides matching titles, descriptions, and tags from discovery.</small></label><label>Blocked creators<Textarea value={creators} onChange={e=>setCreators(e.target.value)} placeholder="Exact creator names, separated by commas"/></label><label className="cw-checkbox-label"><Checkbox checked={demos} onCheckedChange={v=>setDemos(v===true)}/> Include demo collections in discovery</label><Button type="submit" className="cw-primary" disabled={saving}>{saving?'Saving…':'Save preferences'}<Check size={17}/></Button></form><article className="cw-panel"><span className="cw-status">NOT CONNECTED</span><h2>Community moderation</h2><p className="cw-muted">AT Protocol labelers will let communities layer their own rules on top of baseline platform safety.</p><p className="cw-muted">This version applies personal filters to discovery. It does not scan uploaded content or replace moderation, abuse reporting, or takedown processes.</p><div className="cw-info"><LockKeyhole size={20}/> Labeler subscriptions, reporting queues, appeals, and platform-wide enforcement require production implementation.</div></article></div>;
}

function Viewer({item,preferences,saving,onToggle,onRemix,onIntegration,onBlock}:{item:Item;preferences:Preferences;saving:boolean;onToggle:(k:'liked'|'saved',id:string)=>Promise<void>;onRemix:()=>void;onIntegration:()=>void;onBlock:()=>Promise<void>}) {
 const [comments,setComments]=useState<{id:string;body:string;creator:string}[]>([]);const [body,setBody]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{let current=true;setComments([]);setError('');api<typeof comments>(`/creator/items/${item.id}/comments`).then(c=>{if(current)setComments(c);}).catch(e=>{if(current)setError(e.message);});return()=>{current=false;};},[item.id]);
 async function comment(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const row=await api<(typeof comments)[0]>(`/creator/items/${item.id}/comments`,{body});setComments([row,...comments]);setBody('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="cw-viewer"><MediaPlayer key={item.id} item={item}/><div className="cw-viewer-details"><div className="cw-viewer-creator"><span className="cw-avatar">{item.creator[0]}</span><div><strong>{item.creator}</strong><small>{item.label}</small></div></div><p>{item.description}</p><div className="cw-tags">{item.tags.map(t=><span key={t}>#{t}</span>)}</div>{item.price_cents!=null&&<p>Display price: ${(item.price_cents/100).toFixed(2)} USD · checkout unavailable</p>}{item.remix_of&&<p className="cw-muted">Attributed remix · source {item.remix_of}</p>}<div className="cw-viewer-actions"><Button variant="outline" disabled={saving} onClick={()=>void onToggle('liked',item.id)} aria-pressed={preferences.liked.includes(item.id)}><Heart size={17} fill={preferences.liked.includes(item.id)?'currentColor':'none'}/> Like</Button><Button variant="outline" disabled={saving} onClick={()=>void onToggle('saved',item.id)} aria-pressed={preferences.saved.includes(item.id)}><Bookmark size={17} fill={preferences.saved.includes(item.id)?'currentColor':'none'}/> Save</Button><Button variant="outline" onClick={onRemix}><Scissors size={17}/> Remix</Button></div><Button variant="ghost" className="cw-integration-link" onClick={onIntegration}><Wallet size={16}/> Tips & subscriptions · not connected <ArrowUpRight size={14}/></Button><div className="cw-comments"><h3><MessageCircle size={17}/> Conversation <span>{comments.length}</span></h3><form onSubmit={comment}><Input aria-label="Write a comment" value={body} onChange={e=>setBody(e.target.value)} maxLength={1000} required placeholder="Add to the conversation…"/><Button type="submit" className="cw-primary" disabled={busy}>Post</Button></form>{error&&<p role="alert" className="cw-error">{error}</p>}{comments.length?comments.map(c=><div className="cw-comment" key={c.id}><strong>{c.creator}</strong><p>{c.body}</p></div>):<p className="cw-muted">Start a conversation. Comments stay on this local installation.</p>}</div><Button variant="ghost" disabled={saving} onClick={()=>void onBlock()}><ShieldCheck size={15}/> Hide this creator from my feed</Button></div></div>;
}

