import { StyleSheet } from "react-native";
export const color = {
  bg: "#120D1F",
  panel: "#211C2C",
  raised: "#2C213B",
  border: "#383040",
  text: "#FAF7FF",
  muted: "#B5A8C7",
  faint: "#87789A",
  purple: "#5420AB",
  lime: "#A6E21B",
  danger: "#FFA6A6",
};
export const font = {
  regular: "Barlow",
  medium: "BarlowMedium",
  semibold: "BarlowSemiBold",
  bold: "BarlowBold",
};
export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: color.bg },
  page: { padding: 22, paddingBottom: 32, gap: 22 },
  title: {
    fontFamily: font.bold,
    color: color.text,
    fontSize: 36,
    lineHeight: 39,
    letterSpacing: -1,
  },
  heading: {
    fontFamily: font.semibold,
    color: color.text,
    fontSize: 24,
    letterSpacing: -0.5,
  },
  body: {
    fontFamily: font.regular,
    color: color.muted,
    fontSize: 16,
    lineHeight: 24,
  },
  small: {
    fontFamily: font.regular,
    color: color.muted,
    fontSize: 13,
    lineHeight: 19,
  },
  eyebrow: {
    fontFamily: font.medium,
    color: color.lime,
    fontSize: 11,
    letterSpacing: 1.5,
  },
  row: { flexDirection: "row", alignItems: "center", gap: 12 },
  between: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  panel: {
    backgroundColor: color.panel,
    borderColor: color.border,
    borderWidth: 1,
    padding: 20,
    borderRadius: 22,
    gap: 14,
  },
  label: {
    color: color.text,
    fontFamily: font.medium,
    fontSize: 14,
    marginBottom: 8,
  },
  input: {
    backgroundColor: color.panel,
    borderWidth: 1,
    borderColor: color.border,
    borderRadius: 13,
    paddingHorizontal: 15,
    paddingVertical: 13,
    color: color.text,
    fontFamily: font.regular,
    fontSize: 16,
    minHeight: 50,
  },
  error: {
    color: color.danger,
    fontFamily: font.regular,
    fontSize: 14,
    lineHeight: 21,
  },
  separator: { height: 1, backgroundColor: color.border },
});
